version: "3.8"

services:
  app:
    image: sheikhvalora/tribel-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: tribel
    depends_on:
      - redis

  redis:
    image: redis:7.4.8-alpine
    ports:
      - "6379:6379"
    container_name: redis-server
    volumes:
      - redis-data:/data
    env_file:
      - .env
    command: sh -c 'redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"'
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq-server
    restart: unless-stopped
    env_file:
       - .env
    environment:
       RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
       RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  redis-data:
  rabbitmq-data:
